<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VirginActive.Rocks.Application\VirginActive.Rocks.Application.csproj" />
    <ProjectReference Include="..\VirginActive.Rocks.Domain\VirginActive.Rocks.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
